
## load external properties
#load:
#  properties: ${user.home}/config/my-application.properties
ebean:
  dbSchema: ${db.username:postgres}
  migration.run: false

datasource:
  db:
    username: ${db.username:postgres}
    password: ${db.password:1111}
    url: ${db.url:jdbc:postgresql://localhost:5432/oftalmologia}

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1111
    volumes:
    - pgdata:/var/lib/postgresql/data

  volumes:
    pgdata:

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
#ebean:
#  docstore:
#    url: http://127.0.0.1:9200
#    active: true
#  migration:
#   run: true




